# NOTE: Generated By HttpRunner v4.3.5
# FROM: testcases/upload_testcase.yml
from httprunner import HttpRunner, Config, Step
from httprunner import (
    RunRequest,
)


class TestCaseUploadTestcase(HttpRunner):

    config = Config("test upload file with httpbin").variables(
        **{"test_file": "data/test.env", "base_url": "https://httpbin.org"}
    )

    teststeps = [
        Step(
            RunRequest("upload file with keyword")
            .post("$base_url/post")
            .upload(**{"file": "test.env"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_startswith("body.form.file", "test")
        ),
    ]


if __name__ == "__main__":
    TestCaseUploadTestcase().test_start()
